In [4]:
import numpy as np
array = np.arange(0,10)

In [5]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array[2:4]

array([2, 3])

In [7]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array[5:]

array([5, 6, 7, 8, 9])

In [9]:
array[:4]

array([0, 1, 2, 3])

In [10]:
array2 = array.copy()

In [11]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array2[0] = 100


In [13]:
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [14]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])