In [1]:
import numpy as np

In [2]:
array = np.random.randint(1,100,25)

In [3]:
array

array([98,  8, 62, 10, 73, 26, 57, 26, 22, 83, 54, 23, 21, 93, 32, 68, 68,
       90, 96, 20, 96, 37, 24, 21, 40])

In [7]:
matriz = array.reshape(5,5)

In [8]:
matriz

array([[98,  8, 62, 10, 73],
       [26, 57, 26, 22, 83],
       [54, 23, 21, 93, 32],
       [68, 68, 90, 96, 20],
       [96, 37, 24, 21, 40]])

In [9]:
array = np.random.randint(1,100,50)

In [10]:
array

array([ 3, 91, 27, 37, 83, 84,  5, 85, 80, 14,  2, 48, 22, 22, 71, 32,  2,
       49, 88, 89,  7,  4, 47, 39, 99, 33, 39, 71, 45, 74, 98, 31,  9, 47,
       78, 34, 49, 82, 96, 46, 88, 20, 43, 62, 23, 35,  8, 15, 17, 10])

In [11]:
matriz1 = array.reshape(5,10)

In [12]:
matriz1

array([[ 3, 91, 27, 37, 83, 84,  5, 85, 80, 14],
       [ 2, 48, 22, 22, 71, 32,  2, 49, 88, 89],
       [ 7,  4, 47, 39, 99, 33, 39, 71, 45, 74],
       [98, 31,  9, 47, 78, 34, 49, 82, 96, 46],
       [88, 20, 43, 62, 23, 35,  8, 15, 17, 10]])

In [13]:
valor_maximo = matriz1.max()

In [14]:
valor_maximo

99

In [15]:
posicion_valor_maximo = array.argmax()

In [17]:
posicion_valor_maximo

24

In [18]:
valor_minimo = matriz1.min()

In [19]:
valor_minimo

2

In [20]:
posicion_valor_minimo = array.argmin()

In [21]:
posicion_valor_minimo

10