In [1]:
#Numpy Arrays

In [2]:
import numpy as np

In [4]:
lista = [1,2,3,4]

In [5]:
array = np.array(lista)

In [6]:
array

array([1, 2, 3, 4])

In [7]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
array = np.array(lista2)

In [10]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
hola = np.array(lista2)

In [12]:
hola

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])