In [1]:
import numpy as np


In [2]:
array = np.arange(0,10)

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
condicion = array > 5

In [5]:
condicion 

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
array[condicion]

array([6, 7, 8, 9])

In [9]:
array6 = array[condicion]

In [10]:
array6

array([6, 7, 8, 9])

In [11]:
array[array % 2 ==0]

array([0, 2, 4, 6, 8])